### ISSUE TITLE
Supporter d'autres instances ?

### ISSUE THREAD

**Issue by OlivierNicole** [Cerdic/pouetradio#6]
Serait-il envisageable de supporter d'autres instances que mamot.fr ? Est-ce que ça présente des difficultés techniques ?

**Comment by Cerdic** [comment]
La radio n'est pas limitée à une instance, même si elle se connecte de fait sur l'instance @mamot.fr pour récupérer les pouets.
Mais tous les comptes visibles depuis cette instance apparaissent normalement dans la pouetradio.

Pour contourner les problèmes éventuels de visibilité quand les tags d'un compte ne remonte pas dans la radio, il suffit de suivre le compte https://mamot.fr/@pouetradio
il y a en principe un autofollow (c'est à dire que le compte @pouetradio va lui même suivre automatiquement tous les comptes qui le suivent, avec un délai de 24h maxi), qui doit permettre de faire remonter les pouets des comptes concernés.

Je n'ai pas encore indiqué cela dans la doc car je n'ai pas vraiment testé, mais c'est en principe fonctionnel !

**Comment by Cerdic** [comment]
Ça fonctionne maintenant : tout utilisateur qui poste sur #pouetradio est automatiquement suivi et si jamais quelqu'un n'est pas vu il suffit qu'il follow @pouetradio pour être suivi en retour et que ses pouets soient bien visible dans le flux
