### ISSUE TITLE
Ignorer/contourner le bloquage géographique

### ISSUE THREAD

**Issue by lenod** [Cerdic/pouetradio#7]
De nombreuses vidéos sont bloquées dans certains pays (ce que le gens qui postent ne réalisent pas).
La lecture est alors arrêtée et il faut passer manuellement à la prochaine chanson qui fonctionne.

Est-ce qu'il serait possible soit :
- détecter ça, et passer automatiquement à la chanson suivante
- ou contourner le blocage (en passant par hooktube par exemple)

**Comment by Cerdic** [comment]
Faut que je creuse voir si l'API du lecteur audio permet de détecter le blocage, mais en première approche quand j'ai regardé je n'avais pas trouvé.

Par contre le contournement du blocage je vois pas du tout comment ce serait possible. Je ne pense pas que hooktube fournisse toute l'API de youtube et permette de jouer une vidéo dans le player depuis ses URLs.

**Comment by stragu** [comment]
Lié à ça, il y des restrictions qui font que certaines vidéos sont seulement jouables sur YouTube (comme les vidéos Vevo), voir par exemple https://pouet.audio/#item19353, ce qui bloque le passage à l'élément suivant.

Est-ce que ça devrait être un ticket séparé ?

**Comment by Cerdic** [comment]
C'est tout bon je crois : les sons youtube sont joués depuis la source mp4 (mais chut) et on saute au morceau suivant quand on voit qu'au bout de 7.5secondes la lecture est toujours bloquée (tempo expérimentale)
